# Generated by Django 2.0.7 on 2018-07-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conment',
            new_name='Comment',
        ),
    ]
